package application;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
/** Starting the spring boot Application.*/

@SpringBootApplication
@ComponentScan(basePackages = "controller")
public class Application {
/** Main Class.
* @param args **this is an argument of application**.
*/
public static void main(final String[] args) {
SpringApplication.run(Application.class, args);
}
}